## static_territories
UPDATE static_territories SET tr_name_no='Afrika' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_no='Oseania' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_no='Nord-, Sentral- og Sør-Amerika' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_no='Asia' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_no='Europa' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_no='Østasia' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_no='Sørøst-Asia' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_no='0' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_no='Vest-Asia' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_no='Sør-Europa' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_no='Øst-Europa' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_no='Nord-Europa' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_no='Vest-Europa' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_no='Sør-Amerika' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_no='Sentral-Amerika' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_no='Nord-Amerika' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_no='Karibia' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_no='Vest-Afrika' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_no='Øst-Afrika' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_no='Nord-Afrika' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_no='Sentral-Afrika' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_no='Sør-Afrika' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_no='Australia og New Zealand' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_no='Melanesia' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_no='Mikronesia' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_no='Polynesia' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_no='0' WHERE tr_iso_nr='34';

## static_countries
UPDATE static_countries SET cn_short_no='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_no='De forente arabiske emirater' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_no='Afghanistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_no='Antigua og Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_no='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_no='Albania' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_no='Armenia' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_no='Nederlandske antiller' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_no='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_no='Antarktika' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_no='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_no='Amerikansk Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_no='Østerrike' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_no='Australia' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_no='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_no='Åland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_no='Aserbajdsjan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_no='Bosnia-Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_no='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_no='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_no='Belgia' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_no='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_no='Bulgaria' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_no='Bahrain' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_no='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_no='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_no='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_no='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_no='Bolivia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_no='Brasil' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_no='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_no='Bhutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_no='Bouvetøya' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_no='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_no='Hviterussland' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_no='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_no='Canada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_no='Kokosøyene' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_no='Kongo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_no='Den sentralafrikanske republikk' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_no='Kongo-Brazzaville' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_no='Sveits' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_no='Elfenbenskysten' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_no='Cookøyene' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_no='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_no='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_no='Kina' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_no='Colombia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_no='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_no='Serbia og Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_no='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_no='Kapp Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_no='Christmasøya' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_no='Kypros' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_no='Tsjekkia' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_no='Tyskland' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_no='Djibouti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_no='Danmark' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_no='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_no='Den dominikanske republikk' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_no='Algerie' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_no='Ecuador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_no='Estland' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_no='Egypt' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_no='Vest-Sahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_no='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_no='Spania' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_no='Etiopia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_no='' WHERE cn_iso_2='EU';
UPDATE static_countries SET cn_short_no='Finland' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_no='Fiji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_no='Falklandsøyene' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_no='Mikronesiaføderasjonen' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_no='Færøyene' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_no='Frankrike' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_no='FX' WHERE cn_iso_2='FX';
UPDATE static_countries SET cn_short_no='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_no='Storbritannia' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_no='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_no='Georgia' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_no='Fransk Guyana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_no='Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_no='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_no='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_no='Grønland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_no='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_no='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_no='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_no='Ekvatorial-Guinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_no='Hellas' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_no='Sør-Georgia og Sør-Sandwichøyene' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_no='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_no='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_no='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_no='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_no='Hongkong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_no='HM' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_no='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_no='Kroatia' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_no='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_no='Ungarn' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_no='Indonesia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_no='Irland' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_no='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_no='Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_no='India' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_no='IO' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_no='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_no='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_no='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_no='Italia' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_no='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_no='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_no='Jordan' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_no='Japan' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_no='Kenya' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_no='Kirgistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_no='Kambodsja' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_no='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_no='Komorene' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_no='Saint Kitts og Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_no='Nord-Korea' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_no='Sør-Korea' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_no='Kuwait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_no='Caymanøyene' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_no='Kasakhstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_no='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_no='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_no='Saint Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_no='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_no='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_no='Liberia' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_no='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_no='Litauen' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_no='Luxembourg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_no='Latvia' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_no='Libya' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_no='Marokko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_no='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_no='Moldova' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_no='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_no='Marshalløyene' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_no='Makedonia' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_no='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_no='Burma' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_no='Mongolia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_no='Macao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_no='Nord-Marianene' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_no='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_no='Mauritania' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_no='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_no='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_no='Mauritius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_no='Maldivene' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_no='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_no='Mexico' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_no='Malaysia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_no='Mosambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_no='Namibia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_no='Ny-Caledonia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_no='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_no='Norfolk Island' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_no='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_no='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_no='Nederland' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_no='Norge' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_no='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_no='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_no='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_no='New Zealand' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_no='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_no='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_no='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_no='Fransk Polynesia' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_no='Papua Ny-Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_no='Filippinene' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_no='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_no='Polen' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_no='Saint-Pierre-et-Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_no='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_no='Puerto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_no='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_no='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_no='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_no='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_no='Qatar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_no='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_no='Romania' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_no='Russland' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_no='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_no='Saudi-Arabia' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_no='Salomonøyene' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_no='Seychellene' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_no='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_no='Sverige' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_no='Singapore' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_no='St. Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_no='Slovenia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_no='Svalbard og Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_no='Slovakia' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_no='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_no='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_no='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_no='Somalia' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_no='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_no='São Tomé og Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_no='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_no='Syria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_no='Swaziland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_no='Turks- og Caicosøyene' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_no='Tsjad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_no='Franske sydlige territorier' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_no='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_no='Thailand' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_no='Tadsjikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_no='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_no='Øst-Timor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_no='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_no='Tunisia' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_no='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_no='Tyrkia' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_no='Trinidad og Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_no='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_no='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_no='Tanzania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_no='Ukraina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_no='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_no='Storbritannia' WHERE cn_iso_2='UK';
UPDATE static_countries SET cn_short_no='De forente staters mindre utenforliggende øyer' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_no='De forente stater' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_no='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_no='Usbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_no='Vatikanstaten' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_no='Saint Vincent og Grenadinene' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_no='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_no='Jomfruøyene (Britisk)' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_no='Jomfruøyene (USA)' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_no='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_no='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_no='Wallis- og Futunaøyene' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_no='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_no='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_no='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_no='Sør-Afrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_no='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_no='Zimbabwe' WHERE cn_iso_2='ZW';


## static_country_zones
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='AK';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='AZ';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='DE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='DC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='FL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='GA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='GU';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='HI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='ID';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='IL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='IN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='IA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='KS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='KY';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='LA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='MD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='NV';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='NH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='NJ';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='NM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='NY';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='NC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='ND';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='OH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='OK';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='SD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='TX';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='UT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='WV';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='US' AND zn_code='WY';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='AB';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='MB';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='NF';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='NB';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='NS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='ON';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='QC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='SK';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CA' AND zn_code='YT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='NDS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='BAW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='BAY';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='BER';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='BRG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='BRE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='HAM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='HES';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='MEC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='NRW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='RHE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='SAR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='SAS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='SAC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='SCN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='DE' AND zn_code='THE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AT' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AT' AND zn_code='OO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AT' AND zn_code='SB';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AT' AND zn_code='KN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AT' AND zn_code='ST';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AT' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AT' AND zn_code='VB';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='AI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='BE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='GL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='JU';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='NW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='OW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='SG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='SH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='SZ';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='TG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='UR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='VD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='VS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='ZG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='CH' AND zn_code='ZH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Alava';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Malaga';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Segovia';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Granada';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Jaen';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Sevilla';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Barcelona';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Valencia';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Alicante';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Almeria';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Asturias';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Avila';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Badajoz';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Burgos';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Caceres';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Cadiz';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Cantabria';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Castellon';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Ceuta';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Ciudad Real';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Cordoba';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Cuenca';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Girona';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Las Palmas';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Guadalajara';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Guipuzcoa';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Huelva';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Huesca';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='A Coruña';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='La Rioja';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Leon';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Lugo';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Lleida';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Madrid';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Baleares';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Murcia';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Navarra';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Ourense';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Palencia';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Pontevedra';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Salamanca';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Soria';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Tarragona';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Tenerife';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Teruel';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Toledo';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Valladolid';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Vizcaya';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Zamora';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Zaragoza';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='ES' AND zn_code='Melilla';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='AGS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='BCS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='CAM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='CHIS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='CHIH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='COAH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='COL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='DIF';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='DGO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='GTO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='GRO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='HGO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='JAL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='MEX';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='MICH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='MOR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='NAY';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='NL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='OAX';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='PUE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='QRO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='QROO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='SLP';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='SIN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='SON';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='TAB';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='TAMPS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='TLAX';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='VER';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='YUC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='MX' AND zn_code='ZAC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AU' AND zn_code='ACT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AU' AND zn_code='NSW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AU' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AU' AND zn_code='QLD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AU' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AU' AND zn_code='TAS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AU' AND zn_code='VIC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='AU' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='AN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='AO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='AQ';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='AT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='AV';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='BG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='BI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='BN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='BO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='BR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='BZ';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CB';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='CZ';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='EN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='FE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='FG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='FI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='FO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='IM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='IS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='KR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='LC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='LE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='LI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='LO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='LT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='MC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='NA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PV';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='PZ';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='RA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='RC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='RE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='RG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='RM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='SI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='SR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='SS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='SV';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='TA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='TE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='TO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='TP';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='TR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='TS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='TV';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='UD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='VC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='VE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='VI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='VP';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='VR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IT' AND zn_code='VV';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='ALD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='ARM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='ATM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='BDS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='BFD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='BIR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='BLG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='BRI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='BRK';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='BRS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='BUX';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CAP';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CAS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CBA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CBE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CER';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CHI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CHS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CLD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CNL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CON';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CTR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='CVE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='DEN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='DFD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='DGL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='DHM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='DOR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='DVN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='DWN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='DYS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='ESX';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='FER';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='FFE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='FLI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='FMH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='GDD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='GLO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='GLR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='GNM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='GNS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='GNW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='GRN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='GUR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='GWT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='HBS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='HFD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='HLD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='HPH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='HWR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='IOM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='IOW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='ISL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='JER';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='KNT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='LCN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='LDN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='LDR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='LEC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='LNH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='LTE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='LTM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='LTW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='MCH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='MER';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='MSY';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='NET';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='NEW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='NHM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='NLD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='NOR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='NOT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='NWH';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='OFE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='ORK';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='PEM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='PWS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SCD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SFD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SFK';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SLD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SOM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SPE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SRK';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SRY';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SWA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SXE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='SXW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='TAF';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='TOR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='TWR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='TYR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='TYS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='VAL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='WIL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='WKS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='WLT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='WMD';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='WRE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='YSN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='YSS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='GB' AND zn_code='YSW';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='CAV';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='CLA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='COR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='DON';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='DUB';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='GAL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='KER';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='KIL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='KLK';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='LAO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='LEI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='LIM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='LOU';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='MAY';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='MEA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='OFF';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='ROS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='SLI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='TIP';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='WAT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='WES';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='WEX';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='IE' AND zn_code='WIC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='AC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='AM';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='DF';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='ES';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='MG';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='PB';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='RJ';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='RR';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='RS';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='SE';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_no='' WHERE zn_country_iso_2='BR' AND zn_code='TO';


## static_currencies
UPDATE static_currencies SET cu_name_no='Afghansk afghani',cu_sub_name_no='' WHERE cu_iso_3='AFA';
UPDATE static_currencies SET cu_name_no='Albansk lek',cu_sub_name_no='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_no='Algerisk dinar',cu_sub_name_no='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_no='Amerikansk dollar',cu_sub_name_no='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_no='Euro',cu_sub_name_no='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_no='Angolansk kwanza',cu_sub_name_no='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_no='Østkaribisk dollar',cu_sub_name_no='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_no='Argentinsk peso',cu_sub_name_no='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_no='Armensk dram',cu_sub_name_no='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_no='Arubansk florin',cu_sub_name_no='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_no='Australsk dollar',cu_sub_name_no='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_no='Aserbajdsjansk manat',cu_sub_name_no='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_no='Bahamansk dollar',cu_sub_name_no='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_no='Bahrainsk dinar',cu_sub_name_no='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_no='Bangladesisk taka',cu_sub_name_no='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_no='Barbadisk dollar',cu_sub_name_no='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_no='Belizisk dollar',cu_sub_name_no='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_no='CFA-franc',cu_sub_name_no='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_no='Bermudisk dollar',cu_sub_name_no='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_no='Bhutanskngultrum',cu_sub_name_no='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_no='Boliviansk boliviano',cu_sub_name_no='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_no='Bosnisk marka',cu_sub_name_no='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_no='Botswansk pula',cu_sub_name_no='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_no='Brasiliansk real',cu_sub_name_no='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_no='Bruneisk dollar',cu_sub_name_no='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_no='Bulgarsk lev',cu_sub_name_no='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_no='Burundisk franc',cu_sub_name_no='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_no='Canadisk dollar',cu_sub_name_no='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_no='Caymansk dollar',cu_sub_name_no='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_no='Chilensk peso',cu_sub_name_no='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_no='Colombiansk peso',cu_sub_name_no='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_no='Newzealandsk dollar',cu_sub_name_no='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_no='Costaricansk colon',cu_sub_name_no='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_no='Cubansk peso',cu_sub_name_no='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_no='Dansk krone',cu_sub_name_no='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_no='Dominikansk peso',cu_sub_name_no='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_no='Egyptisk pund',cu_sub_name_no='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_no='CFA-franc',cu_sub_name_no='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_no='Eritreisk nakfa',cu_sub_name_no='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_no='Estlandsk krone',cu_sub_name_no='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_no='Etiopisk birr',cu_sub_name_no='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_no='Filippinsk peso',cu_sub_name_no='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_no='Falklandsk pund',cu_sub_name_no='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_no='Fijiansk dollar',cu_sub_name_no='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_no='Emiratarabisk dirham',cu_sub_name_no='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_no='CFP-franc',cu_sub_name_no='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_no='Gambisk dalasi',cu_sub_name_no='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_no='Georgisk lari',cu_sub_name_no='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_no='Ghanesisk cedi',cu_sub_name_no='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_no='Gibraltarsk pund',cu_sub_name_no='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_no='Guatemalansk quetzal',cu_sub_name_no='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_no='Guernsey-pund',cu_sub_name_no='' WHERE cu_iso_3='GGP';
UPDATE static_currencies SET cu_name_no='Guineansk franc',cu_sub_name_no='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_no='Guyansk dollar',cu_sub_name_no='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_no='Haitisk gourde',cu_sub_name_no='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_no='Honduransk lempira',cu_sub_name_no='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_no='Hong Kong-dollar',cu_sub_name_no='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_no='Hviterussisk rubel',cu_sub_name_no='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_no='Indisk rupi',cu_sub_name_no='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_no='Indonesisk rupiah',cu_sub_name_no='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_no='Iransk rial',cu_sub_name_no='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_no='Ny irakisk dinar',cu_sub_name_no='' WHERE cu_iso_3='NID';
UPDATE static_currencies SET cu_name_no='Islandsk krone',cu_sub_name_no='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_no='Israelsk shekel',cu_sub_name_no='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_no='Jamaicansk dollar',cu_sub_name_no='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_no='Japansk yen',cu_sub_name_no='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_no='Jemenittisk rial',cu_sub_name_no='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_no='Jersey-pund',cu_sub_name_no='' WHERE cu_iso_3='JEP';
UPDATE static_currencies SET cu_name_no='Jordansk dinar',cu_sub_name_no='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_no='Kambodsjansk riel',cu_sub_name_no='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_no='Kenyansk shilling',cu_sub_name_no='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_no='Kinesisk yuan renminbi',cu_sub_name_no='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_no='Komorisk franc',cu_sub_name_no='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_no='Kongolesisk franc',cu_sub_name_no='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_no='Kroatisk kuna',cu_sub_name_no='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_no='Kuwaitisk dinar',cu_sub_name_no='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_no='Laotisk kip',cu_sub_name_no='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_no='Latvisk lat',cu_sub_name_no='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_no='Lesothisk loti',cu_sub_name_no='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_no='Libanesisk pund',cu_sub_name_no='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_no='Liberisk dollar',cu_sub_name_no='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_no='Libysk dinar',cu_sub_name_no='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_no='Sveitsisk franc',cu_sub_name_no='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_no='Litauisk litas',cu_sub_name_no='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_no='Ariary',cu_sub_name_no='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_no='Makedonsk denar',cu_sub_name_no='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_no='Malawisk kwacha',cu_sub_name_no='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_no='Ringgit',cu_sub_name_no='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_no='Maldivisk rufiyaa',cu_sub_name_no='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_no='Man-pund',cu_sub_name_no='' WHERE cu_iso_3='IMP';
UPDATE static_currencies SET cu_name_no='Marokkansk dirham',cu_sub_name_no='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_no='Mauritisk rupi',cu_sub_name_no='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_no='Meksikansk peso',cu_sub_name_no='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_no='Moldovsk leu',cu_sub_name_no='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_no='Mongolsk tugrik',cu_sub_name_no='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_no='Mosambikisk metical',cu_sub_name_no='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_no='Myanmarsk kyat',cu_sub_name_no='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_no='Namibisk dollar',cu_sub_name_no='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_no='Antilliansk gylden',cu_sub_name_no='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_no='Nepalsk rupi',cu_sub_name_no='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_no='Nicaraguansk cordoba',cu_sub_name_no='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_no='Nigeriansk naira',cu_sub_name_no='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_no='Nordkoreansk won',cu_sub_name_no='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_no='Norsk krone',cu_sub_name_no='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_no='Omansk rial',cu_sub_name_no='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_no='Pakistansk rupi',cu_sub_name_no='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_no='Panamansk balboa',cu_sub_name_no='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_no='Papuansk kina',cu_sub_name_no='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_no='Paraguayansk guarani',cu_sub_name_no='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_no='Peruansk nuevo sol',cu_sub_name_no='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_no='Polsk zloty',cu_sub_name_no='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_no='Qatarsk Riyal',cu_sub_name_no='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_no='Rumensk leu',cu_sub_name_no='' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_no='Russisk rubel',cu_sub_name_no='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_no='Rwandisk franc',cu_sub_name_no='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_no='Sankthelensk pund',cu_sub_name_no='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_no='Salomonsk dollar',cu_sub_name_no='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_no='Samoansk tala',cu_sub_name_no='' WHERE cu_iso_3='SAT';
UPDATE static_currencies SET cu_name_no='Saotomesisk dobra',cu_sub_name_no='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_no='Saudiarabisk riyal',cu_sub_name_no='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_no='Serbisk dinar',cu_sub_name_no='' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_no='Sierraleonsk leone',cu_sub_name_no='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_no='Singaporsk dollar',cu_sub_name_no='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_no='Slovakisk koruna',cu_sub_name_no='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_no='Srilankisk rupi',cu_sub_name_no='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_no='Britisk pund',cu_sub_name_no='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_no='Sudansk dinar',cu_sub_name_no='' WHERE cu_iso_3='SDD';
UPDATE static_currencies SET cu_name_no='Surinamsk gylden',cu_sub_name_no='' WHERE cu_iso_3='SRG';
UPDATE static_currencies SET cu_name_no='Svensk krone',cu_sub_name_no='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_no='Swazilandsk lilangeni',cu_sub_name_no='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_no='Syrisk pund',cu_sub_name_no='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_no='Sørafrikansk rand',cu_sub_name_no='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_no='Sørkoreansk won',cu_sub_name_no='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_no='Taiwansk dollar',cu_sub_name_no='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_no='Tanzaniansk shilling',cu_sub_name_no='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_no='Thailandsk bath',cu_sub_name_no='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_no='Tongansk paanga',cu_sub_name_no='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_no='Trinidadisk dollar',cu_sub_name_no='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_no='Tsjekkisk koruna',cu_sub_name_no='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_no='Tunisisk dinar',cu_sub_name_no='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_no='Tyrkisk lira',cu_sub_name_no='' WHERE cu_iso_3='TRL';
UPDATE static_currencies SET cu_name_no='Turkmensk manat',cu_sub_name_no='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_no='Ugandisk shilling',cu_sub_name_no='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_no='Ukrainsk hryvnia',cu_sub_name_no='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_no='Ungarsk forint',cu_sub_name_no='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_no='Uruguayansk peso',cu_sub_name_no='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_no='Usbekisk sum',cu_sub_name_no='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_no='Vanuatisk vatu',cu_sub_name_no='' WHERE cu_iso_3='UVU';
UPDATE static_currencies SET cu_name_no='Venezuelansk bolivar',cu_sub_name_no='' WHERE cu_iso_3='VEB';
UPDATE static_currencies SET cu_name_no='Vietnamesisk dong',cu_sub_name_no='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_no='Zambisk kwacha',cu_sub_name_no='' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_no='Zimbabwisk dollar',cu_sub_name_no='' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_no='Kapp Verde Escudo',cu_sub_name_no='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_no='Kypriotisk pund',cu_sub_name_no='' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_no='Djibouti franc',cu_sub_name_no='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_no='Guinea-Bissau Peso',cu_sub_name_no='' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_no='Irakisk dinar',cu_sub_name_no='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_no='Kirgisisk som',cu_sub_name_no='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_no='Khasakstansk tenge',cu_sub_name_no='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_no='Makanesisk pataca',cu_sub_name_no='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_no='Mauretansk ougiya',cu_sub_name_no='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_no='Maltesisk lire',cu_sub_name_no='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_no='Seychellisk rupi',cu_sub_name_no='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_no='Slovensk tolar',cu_sub_name_no='' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_no='Somalisk shilling',cu_sub_name_no='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_no='Salvadorisk colón',cu_sub_name_no='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_no='Tajikistansk somoni',cu_sub_name_no='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_no='Vatu',cu_sub_name_no='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_no='Samoisk tala',cu_sub_name_no='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_no='Afghansk afghani',cu_sub_name_no='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_no='Surinamisk dollar',cu_sub_name_no='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_no='Tyrkisk ny lire',cu_sub_name_no='' WHERE cu_iso_3='TRY';


## static_languages
UPDATE static_languages SET lg_name_no='Afar' WHERE lg_iso_2='AA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Abkhasisk' WHERE lg_iso_2='AB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Avestisk' WHERE lg_iso_2='AE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Afrikaans' WHERE lg_iso_2='AF' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Akan' WHERE lg_iso_2='AK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Amharisk' WHERE lg_iso_2='AM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Aragonesisk' WHERE lg_iso_2='AN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Arabisk' WHERE lg_iso_2='AR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Assamesisk' WHERE lg_iso_2='AS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Avarisk' WHERE lg_iso_2='AV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Aymara' WHERE lg_iso_2='AY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Aserbajdsjansk' WHERE lg_iso_2='AZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Basjkirsk' WHERE lg_iso_2='BA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Hviterussisk' WHERE lg_iso_2='BE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Bulgarsk' WHERE lg_iso_2='BG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Bihari' WHERE lg_iso_2='BH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Bislama' WHERE lg_iso_2='BI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Bambara' WHERE lg_iso_2='BM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Bengali' WHERE lg_iso_2='BN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tibetansk' WHERE lg_iso_2='BO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Bretonsk' WHERE lg_iso_2='BR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Bosnisk' WHERE lg_iso_2='BS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Katalansk' WHERE lg_iso_2='CA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tsjetsjensk' WHERE lg_iso_2='CE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Chamorro' WHERE lg_iso_2='CH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Korsikansk' WHERE lg_iso_2='CO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Cree' WHERE lg_iso_2='CR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tsjekkisk' WHERE lg_iso_2='CS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Gammelslavisk' WHERE lg_iso_2='CU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tsjuvansk' WHERE lg_iso_2='CV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Walisisk' WHERE lg_iso_2='CY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Dansk' WHERE lg_iso_2='DA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tysk' WHERE lg_iso_2='DE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Dhivehi' WHERE lg_iso_2='DV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Dzongkha' WHERE lg_iso_2='DZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Ewe' WHERE lg_iso_2='EE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Gresk' WHERE lg_iso_2='EL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Engelsk' WHERE lg_iso_2='EN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Esperanto' WHERE lg_iso_2='EO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Spansk' WHERE lg_iso_2='ES' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Estisk' WHERE lg_iso_2='ET' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Baskisk' WHERE lg_iso_2='EU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Persisk' WHERE lg_iso_2='FA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Fulfulde' WHERE lg_iso_2='FF' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Finsk' WHERE lg_iso_2='FI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Fijisk' WHERE lg_iso_2='FJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Færøysk' WHERE lg_iso_2='FO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Fransk' WHERE lg_iso_2='FR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Frisisk' WHERE lg_iso_2='FY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Irsk' WHERE lg_iso_2='GA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Skotsk gælisk' WHERE lg_iso_2='GD' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Galisisk' WHERE lg_iso_2='GL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Guaraní' WHERE lg_iso_2='GN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Gujarati' WHERE lg_iso_2='GU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Mansk' WHERE lg_iso_2='GV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Hausa' WHERE lg_iso_2='HA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Hebraisk' WHERE lg_iso_2='HE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Hindi' WHERE lg_iso_2='HI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Hiri motu' WHERE lg_iso_2='HO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kroatisk' WHERE lg_iso_2='HR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Haitisk kreolsk' WHERE lg_iso_2='HT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Ungarsk' WHERE lg_iso_2='HU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Armensk' WHERE lg_iso_2='HY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Herero' WHERE lg_iso_2='HZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Interlingua' WHERE lg_iso_2='IA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Indonesisk' WHERE lg_iso_2='ID' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Interlingue' WHERE lg_iso_2='IE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Ibo' WHERE lg_iso_2='IG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Yi' WHERE lg_iso_2='II' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Inupiak' WHERE lg_iso_2='IK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Ido' WHERE lg_iso_2='IO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Islandsk' WHERE lg_iso_2='IS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Italiensk' WHERE lg_iso_2='IT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Inuittisk' WHERE lg_iso_2='IU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Japansk' WHERE lg_iso_2='JA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Javanesisk' WHERE lg_iso_2='JV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Georgisk' WHERE lg_iso_2='KA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kongolesisk' WHERE lg_iso_2='KG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Gikuyu' WHERE lg_iso_2='KI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kwanyama' WHERE lg_iso_2='KJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kasakhisk' WHERE lg_iso_2='KK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kalaallisut' WHERE lg_iso_2='KL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Khmer' WHERE lg_iso_2='KM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kannada' WHERE lg_iso_2='KN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Koreansk' WHERE lg_iso_2='KO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kanuri' WHERE lg_iso_2='KR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kashmiri' WHERE lg_iso_2='KS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kurdisk' WHERE lg_iso_2='KU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Komi' WHERE lg_iso_2='KV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kornisk' WHERE lg_iso_2='KW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kirgisisk' WHERE lg_iso_2='KY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Latin' WHERE lg_iso_2='LA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Luxembourgisk' WHERE lg_iso_2='LB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Luganda' WHERE lg_iso_2='LG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Limburgisk' WHERE lg_iso_2='LI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Lingala' WHERE lg_iso_2='LN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Laotisk' WHERE lg_iso_2='LO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Litauisk' WHERE lg_iso_2='LT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Luba-Katanga' WHERE lg_iso_2='LU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Latvisk' WHERE lg_iso_2='LV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Gassisk' WHERE lg_iso_2='MG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Marshallesisk' WHERE lg_iso_2='MH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Maoriski' WHERE lg_iso_2='MI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Makedonsk' WHERE lg_iso_2='MK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Malayalam' WHERE lg_iso_2='ML' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Mongolsk' WHERE lg_iso_2='MN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Moldovsk' WHERE lg_iso_2='MO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Marathi' WHERE lg_iso_2='MR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Malayisk' WHERE lg_iso_2='MS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Maltesisk' WHERE lg_iso_2='MT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Burmesisk' WHERE lg_iso_2='MY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Naurisk' WHERE lg_iso_2='NA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Bokmål' WHERE lg_iso_2='NB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Nord-ndebele' WHERE lg_iso_2='ND' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Nepali' WHERE lg_iso_2='NE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Ndonga' WHERE lg_iso_2='NG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Nederlandsk' WHERE lg_iso_2='NL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Nynorsk' WHERE lg_iso_2='NN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Norsk' WHERE lg_iso_2='NO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Sør-ndebele' WHERE lg_iso_2='NR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Navajo' WHERE lg_iso_2='NV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Chichewa' WHERE lg_iso_2='NY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Oksitansk' WHERE lg_iso_2='OC' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Ojibwa' WHERE lg_iso_2='OJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Oromo' WHERE lg_iso_2='OM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Oriya' WHERE lg_iso_2='OR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Ossetisk' WHERE lg_iso_2='OS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Punjabi' WHERE lg_iso_2='PA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Pali' WHERE lg_iso_2='PI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Polsk' WHERE lg_iso_2='PL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Pashto' WHERE lg_iso_2='PS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Portugisisk' WHERE lg_iso_2='PT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Quechua' WHERE lg_iso_2='QU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Retoromansk' WHERE lg_iso_2='RM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kirundi' WHERE lg_iso_2='RN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Rumensk' WHERE lg_iso_2='RO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Russisk' WHERE lg_iso_2='RU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kinyarwanda' WHERE lg_iso_2='RW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Sanskrit' WHERE lg_iso_2='SA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Sardinsk' WHERE lg_iso_2='SC' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Sindhi' WHERE lg_iso_2='SD' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Nordsamisk' WHERE lg_iso_2='SE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Sango' WHERE lg_iso_2='SG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Serbokroatisk' WHERE lg_iso_2='SH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Singalesisk' WHERE lg_iso_2='SI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Slovakisk' WHERE lg_iso_2='SK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Slovensk' WHERE lg_iso_2='SL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Samoansk' WHERE lg_iso_2='SM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Shona' WHERE lg_iso_2='SN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Somalisk' WHERE lg_iso_2='SO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Albansk' WHERE lg_iso_2='SQ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Serbisk' WHERE lg_iso_2='SR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Swati' WHERE lg_iso_2='SS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Sesotho' WHERE lg_iso_2='ST' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Sundanesisk' WHERE lg_iso_2='SU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Svensk' WHERE lg_iso_2='SV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Swahili' WHERE lg_iso_2='SW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tamilsk' WHERE lg_iso_2='TA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Telugu' WHERE lg_iso_2='TE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tadsjikisk' WHERE lg_iso_2='TG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Thai' WHERE lg_iso_2='TH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tigrinya' WHERE lg_iso_2='TI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Turkmensk' WHERE lg_iso_2='TK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tagalog' WHERE lg_iso_2='TL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tswana' WHERE lg_iso_2='TN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tonganesisk' WHERE lg_iso_2='TO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tyrkisk' WHERE lg_iso_2='TR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tsonga' WHERE lg_iso_2='TS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tatarsk' WHERE lg_iso_2='TT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Twi' WHERE lg_iso_2='TW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Tahitisk' WHERE lg_iso_2='TY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Uighur' WHERE lg_iso_2='UG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Ukrainsk' WHERE lg_iso_2='UK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Urdu' WHERE lg_iso_2='UR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Usbekisk' WHERE lg_iso_2='UZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Venda' WHERE lg_iso_2='VE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Vietnamesisk' WHERE lg_iso_2='VI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Volapük' WHERE lg_iso_2='VO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Vallonsk' WHERE lg_iso_2='WA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Wolof' WHERE lg_iso_2='WO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Xhosa' WHERE lg_iso_2='XH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Jiddisk' WHERE lg_iso_2='YI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Yoruba' WHERE lg_iso_2='YO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Zhuang' WHERE lg_iso_2='ZA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kinesisk' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Zulu' WHERE lg_iso_2='ZU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_no='Kinesisk' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='HK';
UPDATE static_languages SET lg_name_no='Kinesisk' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='CN';
UPDATE static_languages SET lg_name_no='Brasiliansk' WHERE lg_iso_2='PT' AND LG_COUNTRY_ISO_2='BR';
